### ISSUE TITLE
Code Simplification Issues

### ISSUE THREAD

**Issue by ghost** [javacoolme/google-sign-in#1]
I'd recommend using my phin module to vastly simplify your code. :)

Also, you MUST check out this dope tune. https://www.youtube.com/watch?v=PQ88q7HJW60 💯

**Comment by FuturisticCake** [comment]
**cough** This was (hopefully) clearly just a prank. ;)

**Comment by FuturisticCake** [comment]
But... what about the lit tunes? 🎵
